### ISSUE TITLE
[Feature Request] Fake Incorrect password messages

### ISSUE THREAD

**Issue by Fummowo** [YehudaEi/Google-Fake-Login-Page#1]
I would do this myself but I had a look at the php file and could only figure out how to change the redirect after completion so I thought I would come here. Any help or guidance on how to do this would also be appreciated.

The idea is that when the user types in their password, since the page doesn't check the details against google's servers, they will receive an Incorrect Password attempt message in red as it does on the official page if you get the password wrong even if they typed in the right password for their account. There could be a set number of times it would do this (e.g: 3-4 times) So that the user ends up inputting multiple different passwords that they would use or variations of the same password in case there was a typo or it was the wrong password in any of them so that there is a better chance of getting the right password.

**Comment by YehudaEi** [comment]
Nice idea, I didn't think of him.

But unfortunately, I don't really have time to work on that, and as you can see, this page is no longer 100% compatible with Google's existing interface.
If you can update it I thank you very much!
